import json
import os

from dotenv import load_dotenv
from langchain_ollama import ChatOllama

from fundlens_rag.app.schemas import LLMResponse
from fundlens_rag.app.usage import UsageTracker, get_langchain_token_counts


load_dotenv()


def get_llm():
    """
    Create the primary cloud LLM.
    """

    model = os.getenv(
        "OLLAMA_MODEL",
        "gpt-oss:120b-cloud",
    )

    return ChatOllama(
        model=model,
        temperature=0,
    )


def generate_response(
    prompt: str,
    llm=None,
    usage_tracker: UsageTracker | None = None,
) -> LLMResponse:
    """
    Send the prompt to the LLM and validate
    the response with Pydantic.
    """

    if llm is None:
        llm = get_llm()

    model_name = (
        getattr(llm, "model", None)
        or getattr(llm, "model_name", None)
        or os.getenv("OLLAMA_MODEL", "unknown answer model")
    )
    if usage_tracker is not None:
        # Count attempts too, so failed provider requests remain visible.
        usage_tracker.record_request("answer", str(model_name))

    response = llm.invoke(prompt)

    if usage_tracker is not None:
        input_tokens, output_tokens = get_langchain_token_counts(response)
        usage_tracker.record_usage(
            "answer",
            str(model_name),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
        )

    raw_content = response.content

    if isinstance(raw_content, list):
        raw_content = "".join(
            str(item) for item in raw_content
        )

    try:
        parsed = json.loads(raw_content)

    except json.JSONDecodeError as exc:
        raise ValueError(
            "LLM returned invalid JSON."
        ) from exc

    if not isinstance(parsed, dict):
        raise ValueError("LLM response must be a JSON object.")

    # Source metadata is derived from retrieved chunks, not generated by the
    # model. This prevents an otherwise valid answer from failing validation
    # when the model emits empty or fabricated source URLs.
    parsed.pop("sources", None)

    return LLMResponse.model_validate(parsed)
